name: satzung.tex to PDF
on: 
  push:
    paths:
      - 'satzung.tex'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: satzung.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: satzung.pdf
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: gerneated PDF from TEX
          commit_options: '--no-verify --signoff'
          commit_author: Github Action <actions@github.com>
          status_options: '--untracked-files=no'
          skip_dirty_check: true
